version: "3"

services:
  redis:
    image: redis
    environment:
      REDIS_HOST: redis
    networks:
      - back-end
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"

    networks:
      - back-end

  voteapp:
    build: ./vote
    ports:
      - 8501:8501
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - back-end
      - front-end

  resultapp:
    build: ./result
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - back-end
      - front-end

  workerapp:
    build: ./worker
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    networks:
      - back-end

networks:
  front-end:
  back-end:
